#!/bin/bash

## Extended aliases
## Append a trailling 'e' to distinguish them
scripte () {
  if [[ -z "$*" ]]; then
    script --timing="/tmp/$$_typescript.time" -q "/tmp/$$_typescript"
  else
    script "$@"
  fi
} && alias script='scripte'

scriptreplaye () {
  if [[ -z "$*" ]]; then
    scriptreplay --timing="/tmp/$$_typescript.time" -q "/tmp/$$_typescript"
  else
    scriptreplay "$@"
  fi
} && alias scriptreplay='scriptreplaye'

# vim: syntax=sh
# vim: set ts=2 sw=2 tw=80 et :
