#!/bin/bash
# shellcheck disable=SC2026
true

# shellcheck disable=SC2034
color-codes () {
local T='gYw'
local test_args=()

echo -ne "\n            "
echo -ne "     40m"
echo -ne "     41m"
echo -ne "     42m"
echo -ne "     43m"
echo -ne "     44m"
echo -ne "     45m"
echo -ne "     46m"
echo -ne "     47m\n"

for FGs in '   0m' '   1m' '0;30m' '1;30m' '0;31m' '1;31m' '0;32m' '1;32m' '0;33m' '1;33m' '0;34m' '1;34m' '0;35m' '1;35m' '0;36m' '1;36m' '0;37m' '1;37m'
do
  local FG=${FGs// /}
  echo -ne " $FGs \033[$FG  $T  "
    for BG in 40m 41m 42m 43m 44m 45m 46m 47m; do
      echo -ne "$EINS \033[$FG\033[$BG  $T \033[0m\033[$BG \033[0m"
    done
echo
done

}
# vim: syntax=sh
# vim: set ts=2 sw=2 tw=80 et :
