#!/bin/bash

# shellcheck disable=SC2034
ORG_IFS=$IFS

color-codes () {
local T='gYw'
local test_args=()

echo -ne "\n            "
echo -ne "     40m"
echo -ne "     41m"
echo -ne "     42m"
echo -ne "     43m"
echo -ne "     44m"
echo -ne "     45m"
echo -ne "     46m"
echo -ne "     47m\n"

IFS=:
test_args+=('    m')
test_args+=('   1m')
test_args+=('  30m')
test_args+=('1;30m')
test_args+=('  31m')
test_args+=('1;31m')
test_args+=('  32m')
test_args+=('1;32m')
test_args+=('  33m')
test_args+=('1;33m')
test_args+=('  34m')
test_args+=('1;34m')
test_args+=('  35m')
test_args+=('1;35m')
test_args+=('  36m')
test_args+=('1;36m')
test_args+=('  37m')
test_args+=('1;37m')

for FGs in ${test_args[*]}; do
  local FG=${FGs// /}
  echo -ne " $FGs \033[$FG  $T  "
    for BG in 40m 41m 42m 43m 44m 45m 46m 47m; do
      echo -ne "$EINS \033[$FG\033[$BG  $T \033[0m\033[$BG \033[0m"
    done
echo
done

IFS=$OLD_IFS
unset ORG_IFS
export IFS

}

if [[ -v "ORG_IFS" ]]; then
  IFS=$OLD_IFS
  unset ORG_IFS
  export IFS
fi
# vim: syntax=sh
# vim: set ts=2 sw=2 tw=80 et :
