#!/bin/bash

pull () {
  set -e
  set -u

  local ORG_PWD="$PWD"
  cd "$HOME/.dotfiles"

  git add -A

  set +e
  git commit -m "$(whoami)@$(hostname) $(date "+%F %T")"
  if [[ "$?" -eq 1 ]]; then
    echo "Last commit: $(git log -1 --pretty=%s)"
    return
  fi
  set -e

  git push -u origin master

  if [[ ! -d "_gitrepos" ]]; then
    mkdir "_gitrepos"
    cd "$ORG_PWD"
    return
  fi

  cd "_gitrepos"

  TIMESTAMP="$(GIT_WORK_TREE="../" git log -1 --pretty=%s)"
  [[ -d "$TIMESTAMP" ]] ||\
    git clone git+ssh://git@github.com/GnomoP/.dotfiles-kali "$TIMESTAMP"
  ln -sf "_gitrepos/$TIMESTAMP" "../_gitlast"

  # shellcheck disable=SC2010
  if [[ "$(find . -maxdepth 1 -type d | grep -cvx '^.$')" -gt 10 ]]; then
    local dir
    dir="$(find . -maxdepth 1 -type d | grep -vx '^.$' | sort | head -n 1)"

    echo "Directory count is greater than 10"
    echo "Removing '$dir' from _gitrepos"
    rm -rf "$dir"
  fi

  cd "$ORG_PWD"
}

if [[ -n "$1" ]]; then
  pull > /dev/null 2>&1
else
  # Color the output
  pull | \
    GREP_COLOR='1;32' grep -E '\S+@\S+ \d{4}-\d{2}\d{2} \d{2}:\d{2}:\{2}'
fi
# vim: syntax=sh
# vim: set ts=2 sw=2 tw=80 et :
