#!/bin/bash

# shellcheck disable=SC2026
true

pull () {
  set -e
  set -u

  local ORG_PWD="$PWD"
  cd "$HOME/.dotfiles"

  git add -A

  set +e
  git commit -m "$(whoami)@$(hostname) $(date "+%F %T")"
  [[ "$?" -eq 1 ]] &&\
    echo "Last commit: $(git log -1 --pretty=%s)"
  set -e

  git push -u origin master
  [[ ! -d "_gitrepos" ]] &&\
    mkdir "_gitrepos"

  local COMMITNAME
  COMMITNAME="$(git log -1 --pretty=%s)"
  if [[ -z "$(ls -A)" ]] ||\
     [[ ! -d "$COMMITNAME" ]] &&\
     [[ $(( "$(date +%s)" - "$(stat _gitlast -c +%Y)" )) -gt 600 ]]
  then
      cd "_gitrepos"
      git clone git+ssh://git@github.com/GnomoP/.dotfiles-kali "$COMMITNAME"
  else
    return
  fi

  ln -sf "_gitrepos/$COMMITNAME" "../_gitlast"

  # shellcheck disable=SC2010
  if [[ "$(find . -maxdepth 1 -type d | grep -cvx '^.$')" -gt 10 ]]; then
    local dir
    dir="$(find . -maxdepth 1 -type d | grep -vx '^.$' | sort | head -n 1)"

    echo "Directory count is greater than 10"
    echo "Removing '$dir' from _gitrepos"
    rm -rf "$dir"
  fi

  cd "$ORG_PWD"
}

[[ -z "$1" ]] &&
  pull && exit

while [[ -n "$1" ]]; do
  case "$1" in
    '-s' | '--silent')
      pull "/dev/null" "2>&1"
      exit
      ;;

    '-w' | '--write')
      name="$(realpath "$0")"
      name="$(basename "$name")"

      faketty () {
        printf "\n"
        script -qfc "$(printf "%q " "$@")" "/tmp/$$_gitlast.log"
      }

      faketty "$name" &
      tail --pid "$!" -f "/tmp/$$_gitlast.log" | \
        perl -p "$HOME/.tailcolor.pl"

      cp "/tmp/$$_gitlast.log" "$HOME/.dotfiles/_gitlast.log.raw" 2>&1
      col -b < "/tmp/$$_gitlast.log" > "$HOME/.dotfiles/_gitlast.log.raw" 2>&1
      #rm "/tmp/$$_dotfiles_push"

      unset -f faketty
      unset name
      ;;

    *)
      ;;
  esac
  shift
done
# vim: syntax=sh
# vim: set ts=2 sw=2 tw=80 et :
