#!/bin/bash

## Quick and dirty one-liners
alias freeram='free && sync && echo 3 > /proc/sys/vm/drop_caches && free'
alias dirfiles='l | grep -v ^d | grep -v ^t | wc -l'

## Command nicknames
alias pager="\$PAGER"
alias editor="\$EDITOR"

if [[ -n "$VIM_THEME" ]]; then
  alias vim="vim -c 'colorscheme \$VIM_THEME'"
fi

alias todo='todo-txt'
alias wvim='wvim-term'
alias vscode='code'
alias dotpush='dotfiles-push'

## Commonly edited config files
alias vimrc='vim ~/.vimrc'
alias bashrc='vim ~/.bashrc'
alias inputrc='vim ~/.inputrc'
alias srcinit='vim ~/.srcinit'
alias aliases='vim ~/.bash_aliases'
alias gitignore='vim ./.gitignore'
alias srcignore='vim ~/src/_ignore'

## Extended aliases from '25_extended-aliases'
alias script='scripte'
alias scriptreplay='scriptreplaye'

## Refresh shell
alias refresh="REFRESH_SHELL='true' exec \$SHELL"

## bash_it substitutes
alias ra='rails'
alias rapp='rails application'

## Commonly used commands in only a few characters
alias e='echo -ne'
alias g='git'
alias gls='git ls-tree --full-tree'
alias lr='l -R'
alias L='less -f'
alias p='dotfiles-push -w'
alias pf='printf'
alias q='exit'
alias r='refresh'
alias re='reload'
alias t='todo-txt'
alias wv='wvim'
alias x='atool -x'
# vim: syntax=sh
# vim: set ts=2 sw=2 tw=80 et :
