#!/usr/bin/env perl
use strict;
use warnings;

LINE:
  while (<>) {
    s{ (^\+)\ ( .* ) }
     {\e[1;34m$1 \e[0;34m$2 \e[m}ax
  } continue {
    print or die "-p destination: $!\n";
  }
# vim: syntax=perl
# vim: set ts=2 sw=2 tw=80 et :
